#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#define _CRT_SECURE_NO_WARNINGS
int main(void) {
        int count = 0;
        int _71, _72, _73, _74, _75, _76, _87, _88, _89, _80;
        system("clear");
        srand(time(NULL));
        printf("\n\n\nTemperature N Humidity Generator 1.0 by Mobambi\n\n\n");
        printf("Temperature\n\n");
        printf("7F - 1 : ");
        scanf("%d", &_71);
        printf("7F - 2 : ");
        scanf("%d", &_72);
        printf("7F - 3 : ");
        scanf("%d", &_73);
        printf("7F - 4 : ");
        scanf("%d", &_74);
        printf("7F - 5 : ");
        scanf("%d", &_75);
        printf("7F - 6 : ");
        scanf("%d", &_76);
        printf("8F - 7 : ");
        scanf("%d", &_87);
        printf("8F - 8 : ");
        scanf("%d", &_88);
        printf("8F - 9 : ");
        scanf("%d", &_89);
        printf("8F - 10 : ");
        scanf("%d", &_80);
        printf("\n\n");
        printf("7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t\n", (count + 1), _71, (count + 1), (_71 + (rand()%2) - (rand()%1)), (count + 1), (_71 + (rand()%2) - (rand()%1)), (count + 1), (_71 + (rand()%2) - (rand()%1)), (count + 1), (_71 + (rand()%2) - (rand()%1)), (count + 1), (_71 + (rand()%3) - (rand()%2)), (count + 1), (_71 + (rand()%2) - (rand()%1)), (count + 1), (_71 + (rand()%2) - (rand()%1)));
        count = count + 1;
        printf("7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t\n", (count + 1), _72, (count + 1), (_72 + (rand()%2) - (rand()%1)), (count + 1), (_72 + (rand()%2) - (rand()%1)), (count + 1), (_72 + (rand()%2) - (rand()%1)), (count + 1), (_72 + (rand()%2) - (rand()%1)), (count + 1), (_72 + (rand()%3) - (rand()%2)), (count + 1), (_72 + (rand()%2) - (rand()%1)), (count + 1), (_72 + (rand()%2) - (rand()%1)));
        count = count + 1;
        printf("7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t\n", (count + 1), _73, (count + 1), (_73 + (rand()%2) - (rand()%1)), (count + 1), (_73 + (rand()%2) - (rand()%1)), (count + 1), (_73 + (rand()%2) - (rand()%1)), (count + 1), (_73 + (rand()%2) - (rand()%1)), (count + 1), (_73 + (rand()%3) - (rand()%2)), (count + 1), (_73 + (rand()%2) - (rand()%1)), (count + 1), (_73 + (rand()%2) - (rand()%1)));
        count = count + 1;
        printf("7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t\n", (count + 1), _74, (count + 1), (_74 + (rand()%2) - (rand()%1)), (count + 1), (_74 + (rand()%2) - (rand()%1)), (count + 1), (_74 + (rand()%2) - (rand()%1)), (count + 1), (_74 + (rand()%2) - (rand()%1)), (count + 1), (_74 + (rand()%3) - (rand()%2)), (count + 1), (_74 + (rand()%2) - (rand()%1)), (count + 1), (_74 + (rand()%2) - (rand()%1)));
        count = count + 1;
        printf("7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t\n", (count + 1), _75, (count + 1), (_75 + (rand()%2) - (rand()%1)), (count + 1), (_75 + (rand()%2) - (rand()%1)), (count + 1), (_75 + (rand()%2) - (rand()%1)), (count + 1), (_75 + (rand()%2) - (rand()%1)), (count + 1), (_75 + (rand()%3) - (rand()%2)), (count + 1), (_75 + (rand()%2) - (rand()%1)), (count + 1), (_75 + (rand()%2) - (rand()%1)));
        count = count + 1;
        printf("7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t\n", (count + 1), _76, (count + 1), (_76 + (rand()%2) - (rand()%1)), (count + 1), (_76 + (rand()%2) - (rand()%1)), (count + 1), (_76 + (rand()%2) - (rand()%1)), (count + 1), (_76 + (rand()%2) - (rand()%1)), (count + 1), (_76 + (rand()%3) - (rand()%2)), (count + 1), (_76 + (rand()%2) - (rand()%1)), (count + 1), (_76 + (rand()%2) - (rand()%1)));
        count = count + 1;
        printf("8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t\n", (count + 1), _87, (count + 1), (_87 + (rand()%2) - (rand()%1)), (count + 1), (_87 + (rand()%2) - (rand()%1)), (count + 1), (_87 + (rand()%2) - (rand()%1)), (count + 1), (_87 + (rand()%2) - (rand()%1)), (count + 1), (_87 + (rand()%3) - (rand()%2)), (count + 1), (_87 + (rand()%2) - (rand()%1)), (count + 1), (_87 + (rand()%2) - (rand()%1)));
        count = count + 1;
        printf("8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t\n", (count + 1), _88, (count + 1), (_88 + (rand()%2) - (rand()%1)), (count + 1), (_88 + (rand()%2) - (rand()%1)), (count + 1), (_88 + (rand()%2) - (rand()%1)), (count + 1), (_88 + (rand()%2) - (rand()%1)), (count + 1), (_88 + (rand()%3) - (rand()%2)), (count + 1), (_88 + (rand()%2) - (rand()%1)), (count + 1), (_88 + (rand()%2) - (rand()%1)));
        count = count + 1;
        printf("8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t\n", (count + 1), _89, (count + 1), (_89 + (rand()%2) - (rand()%1)), (count + 1), (_89 + (rand()%2) - (rand()%1)), (count + 1), (_89 + (rand()%2) - (rand()%1)), (count + 1), (_89 + (rand()%2) - (rand()%1)), (count + 1), (_89 + (rand()%3) - (rand()%2)), (count + 1), (_89 + (rand()%2) - (rand()%1)), (count + 1), (_89 + (rand()%2) - (rand()%1)));
        count = count + 1;
        printf("8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t\n", (count + 1), _80, (count + 1), (_80 + (rand()%2) - (rand()%1)), (count + 1), (_80 + (rand()%2) - (rand()%1)), (count + 1), (_80 + (rand()%2) - (rand()%1)), (count + 1), (_80 + (rand()%2) - (rand()%1)), (count + 1), (_80 + (rand()%3) - (rand()%2)), (count + 1), (_80 + (rand()%2) - (rand()%1)), (count + 1), (_80 + (rand()%2) - (rand()%1)));
        printf("\n\n\n");
        printf("Humidity\n\n");
        printf("7F - 1 : ");
        scanf("%d", &_71);
        printf("7F - 2 : ");
        scanf("%d", &_72);
        printf("7F - 3 : ");
        scanf("%d", &_73);
        printf("7F - 4 : ");
        scanf("%d", &_74);
        printf("7F - 5 : ");
        scanf("%d", &_75);
        printf("7F - 6 : ");
        scanf("%d", &_76);
        printf("8F - 7 : ");
        scanf("%d", &_87);
        printf("8F - 8 : ");
        scanf("%d", &_88);
        printf("8F - 9 : ");
        scanf("%d", &_89);
        printf("8F - 10 : ");
        scanf("%d", &_80);
        printf("\n\n");
        count = 0;
        printf("7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t\n", (count + 1), _71, (count + 1), (_71 + (rand()%3) - (rand()%3)), (count + 1), (_71 + (rand()%3) - (rand()%3)), (count + 1), (_71 + (rand()%3) - (rand()%3)), (count + 1), (_71 + (rand()%3) - (rand()%3)), (count + 1), (_71 + (rand()%3) - (rand()%3)), (count + 1), (_71 + (rand()%3) - (rand()%3)), (count + 1), (_71 + (rand()%3) - (rand()%3)));
        count = count + 1;
        printf("7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t\n", (count + 1), _72, (count + 1), (_72 + (rand()%3) - (rand()%3)), (count + 1), (_72 + (rand()%3) - (rand()%3)), (count + 1), (_72 + (rand()%3) - (rand()%3)), (count + 1), (_72 + (rand()%3) - (rand()%3)), (count + 1), (_72 + (rand()%3) - (rand()%3)), (count + 1), (_72 + (rand()%3) - (rand()%3)), (count + 1), (_72 + (rand()%3) - (rand()%3)));
        count = count + 1;
        printf("7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t\n", (count + 1), _73, (count + 1), (_73 + (rand()%3) - (rand()%3)), (count + 1), (_73 + (rand()%3) - (rand()%3)), (count + 1), (_73 + (rand()%3) - (rand()%3)), (count + 1), (_73 + (rand()%3) - (rand()%3)), (count + 1), (_73 + (rand()%3) - (rand()%3)), (count + 1), (_73 + (rand()%3) - (rand()%3)), (count + 1), (_73 + (rand()%3) - (rand()%3)));
        count = count + 1;
        printf("7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t\n", (count + 1), _74, (count + 1), (_74 + (rand()%3) - (rand()%3)), (count + 1), (_74 + (rand()%3) - (rand()%3)), (count + 1), (_74 + (rand()%3) - (rand()%3)), (count + 1), (_74 + (rand()%3) - (rand()%3)), (count + 1), (_74 + (rand()%3) - (rand()%3)), (count + 1), (_74 + (rand()%3) - (rand()%3)), (count + 1), (_74 + (rand()%3) - (rand()%3)));
        count = count + 1;
        printf("7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t\n", (count + 1), _75, (count + 1), (_75 + (rand()%3) - (rand()%3)), (count + 1), (_75 + (rand()%3) - (rand()%3)), (count + 1), (_75 + (rand()%3) - (rand()%3)), (count + 1), (_75 + (rand()%3) - (rand()%3)), (count + 1), (_75 + (rand()%3) - (rand()%3)), (count + 1), (_75 + (rand()%3) - (rand()%3)), (count + 1), (_75 + (rand()%3) - (rand()%3)));
        count = count + 1;
        printf("7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t7F - %d = %d\t\n", (count + 1), _76, (count + 1), (_76 + (rand()%3) - (rand()%3)), (count + 1), (_76 + (rand()%3) - (rand()%3)), (count + 1), (_76 + (rand()%3) - (rand()%3)), (count + 1), (_76 + (rand()%3) - (rand()%3)), (count + 1), (_76 + (rand()%3) - (rand()%3)), (count + 1), (_76 + (rand()%3) - (rand()%3)), (count + 1), (_76 + (rand()%3) - (rand()%3)));
        count = count + 1;
        printf("8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t\n", (count + 1), _87, (count + 1), (_87 + (rand()%3) - (rand()%3)), (count + 1), (_87 + (rand()%3) - (rand()%3)), (count + 1), (_87 + (rand()%3) - (rand()%3)), (count + 1), (_87 + (rand()%3) - (rand()%3)), (count + 1), (_87 + (rand()%3) - (rand()%3)), (count + 1), (_87 + (rand()%3) - (rand()%3)), (count + 1), (_87 + (rand()%3) - (rand()%3)));
        count = count + 1;
        printf("8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t\n", (count + 1), _88, (count + 1), (_88 + (rand()%3) - (rand()%3)), (count + 1), (_88 + (rand()%3) - (rand()%3)), (count + 1), (_88 + (rand()%3) - (rand()%3)), (count + 1), (_88 + (rand()%3) - (rand()%3)), (count + 1), (_88 + (rand()%3) - (rand()%3)), (count + 1), (_88 + (rand()%3) - (rand()%3)), (count + 1), (_88 + (rand()%3) - (rand()%3)));
        count = count + 1;
        printf("8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t\n", (count + 1), _89, (count + 1), (_89 + (rand()%3) - (rand()%3)), (count + 1), (_89 + (rand()%3) - (rand()%3)), (count + 1), (_89 + (rand()%3) - (rand()%3)), (count + 1), (_89 + (rand()%3) - (rand()%3)), (count + 1), (_89 + (rand()%3) - (rand()%3)), (count + 1), (_89 + (rand()%3) - (rand()%3)), (count + 1), (_89 + (rand()%3) - (rand()%3)));
        count = count + 1;
        printf("8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t8F - %d = %d\t\n", (count + 1), _80, (count + 1), (_80 + (rand()%3) - (rand()%3)), (count + 1), (_80 + (rand()%3) - (rand()%3)), (count + 1), (_80 + (rand()%3) - (rand()%3)), (count + 1), (_80 + (rand()%3) - (rand()%3)), (count + 1), (_80 + (rand()%3) - (rand()%3)), (count + 1), (_80 + (rand()%3) - (rand()%3)), (count + 1), (_80 + (rand()%3) - (rand()%3)));
printf("\n\n\n");
